In [ ]:
!pip install transformers

from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
text2 = "After months of negotiations the EU finally agreed on Monday to set a price cap on natural gas to protect consumers from excessive price spikes and limit inflationary pressure and industrial damage to European economies The price cap however could limit Europe s capacity to continue to draw most of the global spot LNG supply analysts say Some EU member states such as Germany and the Netherlands had reservations about a price cap concerned that a market intervention and a ceiling on prices would take away Europe s key advantage in attracting LNG supply this year higher prices than in Asia Germany agreed to back the price cap only after the EU also agreed to accelerate permitting rules for renewable energy projects according to EU officials Temporary Price Cap As Of February 15 EU energy ministers have reached a political agreement on a regulation that sets a so called market correction mechanism which would come into force on February 15 2023 The market correction mechanism will be triggered if the month ahead price on the Title Transfer Facility TTF Europe s key benchmark exceeds $191 180 euros per MWh for three working days and the month ahead TTF price is $37 35 euros higher than a reference price for LNG on global markets for the same three working days Related Yergin Oil Prices Could Break $120 If China Overcomes CovidOn Monday the TTF contract for January traded at around $116 110 euros per MWh However if risks to the security of supply occur the European Commission will suspend the price cap rule the EU agreed ADVERTISEMENT Today's agreement clearly signals that Europe is not prepared to pay any price for gas and that it is able to act united to ensure its energy security EU Commissioner for Energy Kadri Simson said Record LNG Imports Into EU The biggest concern of some EU member states has been that a price cap and similar market interventions would make the gas market less transparent and could deprive Europe of LNG supply that has been easily flowing to the EU so far this year The EU s incentive to shake off Russian gas dependence and replace volumes that Russia no longer supplies have made Europe the preferred destination of flexible contract LNG cargoes especially those from the United States More than 70 of all U S LNG exports have headed to Europe in recent months and America is sending record volumes to the EU Between January and November LNG imports into the EU and the UK combined jumped by 65 year over year according to estimates from the Oxford Institute for Energy Studies OIES Imports from the United States alone surged by 176 while imports from other sources grew by 27 In that same period global LNG exports grew by just 5 5 with nearly half of the growth coming from the United States OIES said The key point here is that European LNG imports grew faster than global LNG supply and in particular European LNG imports from the United States grew faster than total U S LNG exports OIES researchers noted in their Quarterly Gas Review this month Europe s ability to attract most of the LNG supply so far this year was helped by high European prices falling LNG demand in Asia including in China and lower imports of LNG in Brazil where hydropower capacity performed better than expected according to OIES China has seen an unprecedented slump in its LNG imports this year and Chinese buyers largely stayed away from spot purchases as inventories ahead of the winter were adequate and demand was lackluster amid snap Covid lockdowns that have slowed industrial demand and economic growth ADVERTISEMENT Low Chinese demand and prohibitively high prices for other Asian buyers such as Pakistan or Bangladesh have created tailwinds for Europe s LNG purchases LNG Market Set To Tighten Next Year In recent weeks however demand in Asia has started to grow China returned to the LNG spot market for next year and the easing of the Covid restrictions in China are likely to intensify competition on the LNG market between the Atlantic and the Pacific basins Europe is building floating LNG import terminals to welcome more cargoes next year but there simply may not be enough LNG supply to flow to Europe when Asian demand rebounds analysts say Even with an anticipated 35 Bcm rise in LNG supply in 2023 Europe is likely to face increasing competition for LNG supply from Asian markets especially China and any LNG supply issues will only exacerbate the situation OIES research fellows wrote Last week Asia s spot LNG prices for February delivery rose by 1 to $38 per million British thermal units MMBtu industry sources told Reuters Chinese giant CNOOC has reportedly bought four to six LNG cargoes for delivery next year in one of the largest spot purchases this year Amid signs of rising demand from Asia the EU gas price cap could bring more risks than benefits The EU said on Monday the cap would be suspended if risks outweigh benefits The exclusion of day ahead and intra day contracts from the mechanism would make it possible for European companies to buy the gas they need in the short term but would still leave consumers exposed to price hikes said Jacob Mandel Senior Associate for Global Energy Markets at Aurora Energy Research And it could keep importers from acquiring gas that needs to be bought in advance such as the LNG cargoes that have kept Europe well supplied so far this winter By Tsvetana Paraskova for Oilprice comMore Top Reads From Oilprice com The Era Of Cheap Oil Has Come To An EndBig Oil Pours Billions In The Permian BasinIs The Texas Grid Well Prepared For Another Arctic Blast".replace("ADVERTISEMENT", "").lower()
text = 'As US energy infrastructure continues to go largely neglected and city populations keep rising certain regions of America are under threat of electricity shortages for several years to come In addition to inadequate energy infrastructure the rise of renewable power sources and the growing countrywide energy demand are putting pressure on the grid like never before The Midwest and South Central U S appear to be most at risk of electricity shortages according to a recent analysis These regions fall into the high risk and elevated risk categories The shortages are most likely to be seen during peak energy usage times according to the North American Electric Reliability Corporation NERC There is a multitude of reasons for the shortages largely centered around America s aging energy infrastructure At present across the Midwest a larger quantity of power generation is going offline than new electricity being brought online This has meant shortages in the region since 2018 In contrast California uses a wide mix of electricity sources including renewable energy options such as solar power which is not consistent In addition the demand varies throughout the day with peak times failing to coincide with high solar power output times The energy issues have also been spurred by a general global shortage of LNG following the Russian invasion of Ukraine and subsequent sanctions on Russian energy Concerns around shortages are mostly based on elevated peak demand which means both higher summer and winter demand peak hour usage and the surge in demand during severe weather events when people are more likely to use their air conditioners and heating systems There are worries that shortages will hit hard in the winter months as power demand in Texas rises by a projected 7 percent over last winter Last year the state s grid operator carried out rotating power outages due to shortages caused by the Texas freeze of February 2021 Related Yergin Oil Prices Could Break $120 If China Overcomes Covid ADVERTISEMENT Meanwhile the Midcontinent Independent System Operator MISO has seen reserve margins decline by 5 percent from last winter NERC stated Energy emergencies [in the region] are likely in extreme conditions And in New England the level of oil stored at power generators was at around 40 percent capacity with NERC suggesting that generators should fill up tanks to prepare Following the winter shortages a greater burden on the grid will likely be seen again in summer 2023 as demand once again increases in the warm weather Several utilities are responding to national and international pressures to shift away from fossil fuels to greener alternatives However with solar and wind power being the most common renewable energy sources in the U S and the development of battery storage facilities in the early stages the variable energy supply and demand make it difficult to ensure consistent electricity delivery In addition much of the U S energy infrastructure requires a major overhaul to make it fit for use as populations grow and different technologies are used to produce energy John Moura the director of reliability assessment at NERC stated We are living in extraordinary times from an electric industry perspective He explained Managing the pace of our generation retirement and our resource mix changes to ensure we have enough energy and essential services are an absolute necessity and added We need to work with the entire ecosystem to make sure we re managing that base and to be very clear that we re not retiring generation prematurely that is done in an orderly fashion and especially in areas that are right on the edge ADVERTISEMENT There have long been concerns about America s aging energy infrastructure not being up to scratch a worry that has heightened in recent years due to more frequent extreme weather events across several states This was an issue when the U S relied predominantly on easily transportable fossil fuels but now that the energy mix is becoming more diversified the energy infrastructure must evolve alongside it This means new transmission lines which can take between seven and 15 years to build The U S must also increase its battery storage capacity by incorporating battery storage in renewable energy operations to ensure a consistent energy supply NERC also highlights the growing amount of electricity being used to mine cryptocurrency suggesting the need for greater regulations on crypto mining and energy use The U S is home to around a third of global crypto asset operations which requires between 0 9 to 1 7 of the country s total electricity usage to mine at present This is equivalent to the usage of all electricity home computers or residential lighting in the U S A combination of factors from aging energy infrastructure to high demand more frequent extreme weather events and LNG shortages are putting increasing pressure on the U S grid While investments are made in modernizing the grid and boosting battery storage alongside renewable energy operations certain regions of the U S are likely to see electricity shortages in peak seasons for several years to come By Felicity Bradstock for Oilprice comMore Top Reads From Oilprice com The Era Of Cheap Oil Has Come To An EndBig Oil Pours Billions In The Permian BasinIs The Texas Grid Well Prepared For Another Arctic Blast'.replace("ADVERTISEMENT", "").lower()

In [ ]:
text3= " A gas pipeline in central Russia that brings gas from Russia's Arctic through Ukraine to Europe has been shut following a huge blast that ripped through and left three people dead and one injured Reuters cited local officials and TASS news agency as reporting According to the Chuvashia regional Emergencies Ministry the pipeline blew up during planned maintenance work near the village of Kalinino about 150 km 90 miles west of the Volga city of Kazan The resulting gas flare has been extinguished with local officials reporting that the flow of gas through the section of the Urengoi Pomary Uzhhorod pipeline was cut off around 1050 GMT Tass reported Later on Tuesday morning a local unit of Gazprom said in a statement carried by Reuters that gas was being diverted to parallel pipelines as a result of the explosion ADVERTISEMENT Built in the 1980s the pipeline enters Ukraine via the Sudzha metering point and currently is the main route for Russian gas to reach Europe State owned gas producer Gazprom and its local branch has however failed to respond to requests for comment Europe probably won t lose too much sleep over it though Gazprom had earlier revealed that it expected to pump 43 million cubic meters of gas to Europe via Ukraine through Sudzha in the next 24 hours a volume in line with recent days ADVERTISEMENT To put that number in context that run rate represents just 5 4 of the 155 billion cubic meters of natural gas that Europe imported from Russia in 2021 Europe has managed to stockpile huge volumes of natural gas for the winter season so much so that prices have tumbled sharply in recent months Whereas supplies of Russian pipeline gas the bulk of Europe s gas imports before the Ukraine war are down to a trickle Europe has been hungrily scooping up Russian LNG in the meantime The Wall Street Journal has reported that the bloc s imports of Russian liquefied natural gas jumped by 41 Y Y in the year through August By Alex Kimani for Oilprice comMore Top Reads From Oilprice com LNG Tanker Orders Soar 95 To Hit A Record High In 2022The Era Of Cheap Oil Has Come To An EndBig Oil Pours Billions In The Permian Basin ".replace("ADVERTISEMENT", "").lower()

In [ ]:
tokenized_sequence = tokenizer.tokenize(text)

In [ ]:
print(tokenized_sequence)

['as', 'us', 'energy', 'infrastructure', 'continues', 'to', 'go', 'largely', 'neglected', 'and', 'city', 'populations', 'keep', 'rising', 'certain', 'regions', 'of', 'america', 'are', 'under', 'threat', 'of', 'electricity', 'shortages', 'for', 'several', 'years', 'to', 'come', 'in', 'addition', 'to', 'inadequate', 'energy', 'infrastructure', 'the', 'rise', 'of', 'renewable', 'power', 'sources', 'and', 'the', 'growing', 'country', '##wide', 'energy', 'demand', 'are', 'putting', 'pressure', 'on', 'the', 'grid', 'like', 'never', 'before', 'the', 'midwest', 'and', 'south', 'central', 'u', 's', 'appear', 'to', 'be', 'most', 'at', 'risk', 'of', 'electricity', 'shortages', 'according', 'to', 'a', 'recent', 'analysis', 'these', 'regions', 'fall', 'into', 'the', 'high', 'risk', 'and', 'elevated', 'risk', 'categories', 'the', 'shortages', 'are', 'most', 'likely', 'to', 'be', 'seen', 'during', 'peak', 'energy', 'usage', 'times', 'according', 'to', 'the', 'north', 'american', 'electric', 'reliabil

In [ ]:
from transformers import BertTokenizer, BertModel

outputs = []

for txt in [text, text2, 
            text3
            ]:
  encoding = tokenizer.encode_plus(txt, add_special_tokens = True,    
                                 truncation = True, padding = "max_length",
                                 return_attention_mask = True, 
                                 return_tensors = "pt"
                                 )

  model = BertModel.from_pretrained("bert-base-uncased")

  # inputs = tokenizer("The capital of France is [MASK].", return_tensors="pt")

  outputs.append(model(**encoding).pooler_output[0])


Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.bias', 'cls.predictions.transform.de

In [ ]:
for o in outputs:
  print(o.size())

torch.Size([768])
torch.Size([768])
torch.Size([768])


In [ ]:
import torch 
x = torch.stack(tuple([o for o in outputs]), 0)


In [ ]:
x

tensor([[-0.6335, -0.5015, -0.9052,  ..., -0.6566, -0.5705,  0.4154],
        [-0.6650, -0.6399, -0.9597,  ..., -0.8406, -0.6324,  0.4328],
        [-0.6900, -0.5827, -0.8204,  ..., -0.5444, -0.5440,  0.4271]],
       grad_fn=<StackBackward0>)

In [ ]:
# WEIGHTS

from numpy import random

random.seed(42)
# W_Q = random.randint(3, size=(x.size()[1], x.size()[0]))
# W_K = random.randint(3, size=(x.size()[1], x.size()[0]))
# W_V = random.randint(3, size=(x.size()[1], x.size()[0]))

W_Q = random.rand(x.size()[1], x.size()[0])
W_K = random.rand(x.size()[1], x.size()[0])
W_V = random.rand(x.size()[1], x.size()[0])

In [ ]:
# transform to tensors

w_key = torch.tensor(W_K, dtype=torch.float32)
w_query = torch.tensor(W_Q, dtype=torch.float32)
w_value = torch.tensor(W_V, dtype=torch.float32)

In [ ]:
# multiply words vector for weight matrices to obtain key, query and values

keys = x @ w_key
querys = x @ w_query
values = x @ w_value

In [ ]:
querys

tensor([[  0.1596,  -8.8983,  -5.3627],
        [ -0.6550, -11.5504,  -7.2498],
        [  1.4448,  -6.2977,  -6.1163]], grad_fn=<MmBackward0>)

In [ ]:
keys

tensor([[ -9.4488,  -4.6506,  -5.7790],
        [-11.2818,  -5.7074,  -9.1127],
        [ -7.5233,  -2.9943,  -5.8317]], grad_fn=<MmBackward0>)

In [ ]:
attn_scores = querys @ keys.T

In [ ]:
attn_scores

tensor([[ 70.8651,  97.8544,  56.7176],
        [101.8014, 139.3779,  81.7924],
        [ 50.9826,  75.3802,  43.6566]], grad_fn=<MmBackward0>)

In [ ]:
from torch.nn.functional import softmax

attn_scores_softmax = softmax(attn_scores, dim=-1)
print(attn_scores_softmax)

tensor([[1.8997e-12, 1.0000e+00, 1.3630e-18],
        [4.7943e-17, 1.0000e+00, 9.7933e-26],
        [2.5369e-11, 1.0000e+00, 1.6697e-14]], grad_fn=<SoftmaxBackward0>)


In [ ]:
weighted_values = values[:, None] * attn_scores_softmax.T[:,:, None]

In [ ]:
weighted_values

tensor([[[-2.2385e-11, -8.2408e-12, -3.3340e-12],
         [-5.6493e-16, -2.0797e-16, -8.4141e-17],
         [-2.9893e-10, -1.1005e-10, -4.4522e-11]],

        [[-1.4535e+01, -6.3633e+00, -2.2931e+00],
         [-1.4535e+01, -6.3633e+00, -2.2931e+00],
         [-1.4535e+01, -6.3633e+00, -2.2931e+00]],

        [[-1.4772e-17, -5.2531e-18, -6.3017e-19],
         [-1.0614e-24, -3.7745e-25, -4.5280e-26],
         [-1.8097e-13, -6.4354e-14, -7.7200e-15]]], grad_fn=<MulBackward0>)

In [ ]:
outputs = weighted_values.sum()

In [ ]:
outputs.item()

-69.5751953125

In [ ]:
cos = torch.nn.CosineSimilarity(dim=-1, eps=1e-8)

In [ ]:
print(softmax(cos(querys, keys.T)*values, dim=-1))

tensor([[2.5098e-04, 9.4235e-02, 9.0551e-01],
        [4.3928e-05, 2.8262e-02, 9.7169e-01],
        [2.0679e-04, 5.4059e-02, 9.4573e-01]], grad_fn=<SoftmaxBackward0>)
